name: "BigQuery Buildkite Plugin"
description: "This Buildkite plugin can be used to deploy tables/views schemas to BigQuery"
author: "Jash Parekh <jash389@gmail.com>"
requirements:
  - bash
configuration:
  properties:
    gcp_project:
      type: string
    dataset_schema_directory:
      type: string
    gcp_service_account:
      type: string
    prod_build_branch:
      type: string
    execute_only_changed_files:
      type: boolean
    fail_pipeline_on_first_exception:
      type: boolean
    custom_image:
      type: string
  required:
    - gcp_project
    - dataset_schema_directory
  additionalProperties: false
