#!/usr/bin/env bash

# Use uv to manage dependencies and create lockfile
uv pip install --system -r requirements.txt
printf "# THIS IS AN AUTOGENERATED LOCKFILE. DO NOT EDIT MANUALLY.\n" >plugin_scripts/requirements.lock
uv pip freeze --system >>plugin_scripts/requirements.lock

echo "Rebuild containers to verify there are no conflicts."
