name: "Publish"
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ./.github/actions/publish_images
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}