name: "Publish"
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Publish
        uses: elgohr/Publish-Docker-Github-Action@2.22
        with:
          name: wayfair-incubator/bigquery-buildkite-plugin
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
